
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:9 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.37.32825.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/daver/source/starfish/win32-build/CMakeFiles/3.27.7/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.37.32825.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/daver/source/starfish/win32-build/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-8e8ul4"
      binary: "C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-8e8ul4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-8e8ul4'
        
        Run Build Command(s): C:/Users/daver/LocalApps/cmake/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_3b20b\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_3b20b.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_3b20b.dir\\build
        Building C object CMakeFiles/cmTC_3b20b.dir/CMakeCCompilerABI.c.obj
        	C:\\Users\\daver\\LocalApps\\cmake\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_3b20b.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-8e8ul4 --filter-prefix="Note: including file: " -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\daver\\AppData\\Local\\Temp\\nmDA73.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_3b20b.exe
        	C:\\Users\\daver\\LocalApps\\cmake\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_3b20b.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_3b20b.dir\\objects1.rsp @C:\\Users\\daver\\AppData\\Local\\Temp\\nmDB8D.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_3b20b.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_3b20b.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_3b20b.dir/manifest.res CMakeFiles\\cmTC_3b20b.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_3b20b.dir\\objects1.rsp /out:cmTC_3b20b.exe /implib:cmTC_3b20b.lib /pdb:C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-8e8ul4\\cmTC_3b20b.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_3b20b.dir/intermediate.manifest CMakeFiles\\cmTC_3b20b.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_3b20b.dir/intermediate.manifest /out:CMakeFiles\\cmTC_3b20b.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_3b20b.dir/manifest.res CMakeFiles\\cmTC_3b20b.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_3b20b.dir\\objects1.rsp /out:cmTC_3b20b.exe /implib:cmTC_3b20b.lib /pdb:C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-8e8ul4\\cmTC_3b20b.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_3b20b.dir/intermediate.manifest CMakeFiles\\cmTC_3b20b.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/daver/LocalApps/cmake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-gadgec"
      binary: "C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-gadgec"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/daver/source/starfish/win32-build/CMakeFiles/CMakeScratch/TryCompile-gadgec'
        
        Run Build Command(s): C:/Users/daver/LocalApps/cmake/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_a0b40\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_a0b40.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_a0b40.dir\\build
        Building CXX object CMakeFiles/cmTC_a0b40.dir/CMakeCXXCompilerABI.cpp.obj
        	C:\\Users\\daver\\LocalApps\\cmake\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_a0b40.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-gadgec --filter-prefix="Note: including file: " -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\daver\\AppData\\Local\\Temp\\nmDEE7.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_a0b40.exe
        	C:\\Users\\daver\\LocalApps\\cmake\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_a0b40.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a0b40.dir\\objects1.rsp @C:\\Users\\daver\\AppData\\Local\\Temp\\nmE011.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_a0b40.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_a0b40.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_a0b40.dir/manifest.res CMakeFiles\\cmTC_a0b40.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a0b40.dir\\objects1.rsp /out:cmTC_a0b40.exe /implib:cmTC_a0b40.lib /pdb:C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-gadgec\\cmTC_a0b40.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a0b40.dir/intermediate.manifest CMakeFiles\\cmTC_a0b40.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_a0b40.dir/intermediate.manifest /out:CMakeFiles\\cmTC_a0b40.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_a0b40.dir/manifest.res CMakeFiles\\cmTC_a0b40.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a0b40.dir\\objects1.rsp /out:cmTC_a0b40.exe /implib:cmTC_a0b40.lib /pdb:C:\\Users\\daver\\source\\starfish\\win32-build\\CMakeFiles\\CMakeScratch\\TryCompile-gadgec\\cmTC_a0b40.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a0b40.dir/intermediate.manifest CMakeFiles\\cmTC_a0b40.dir/manifest.res
        
      exitCode: 0
...
